initial commit

diff --git a/lpass-ssh b/lpass-ssh
--- a/lpass-ssh
+++ b/lpass-ssh
@@ -1,53 +1,47 @@
 #!/usr/bin/env bash
 
-KEY_NAME=$1
+set -e
 
-if ! ( which lpass > /dev/null ); then
-  echo "LastPass CLI is required."
-  exit 2
-fi
-
-# Require something to be passed to this command
-if [ -z "${KEY_NAME}" ]; then
-  echo "You need to specify a key name."
-  exit 2
-fi
-
-# Try to find the passed key path / name
-if ! [ -e "${KEY_NAME}" ]; then
-  if [ -e "${HOME}/.ssh/${KEY_NAME}" ]; then
-    KEY_NAME="${HOME}/.ssh/${KEY_NAME}"
-  else
-    echo "Could not find key file."
-    exit 1
+if [ -z ${SSH_HOURS} ]; then
+  SSH_HOURS=$1
+  if [ -z ${SSH_HOURS} ]; then
+    SSH_HOURS=9
   fi
 fi
 
-# If this key is already in the agent we don't need to do anything
-if ( ssh-add -l | grep -q "${KEY_NAME}" ); then
-  echo "Key already present."
-  exit 0
+if ! ( which lpass > /dev/null ); then
+  echo "LastPass CLI is required."
+  echo "try: brew install lastpass-cli"
+  exit 2
 fi
 
-# Retrieve key from LastPass
-PWD=$(lpass show --field=Passphrase "SSH: $(basename ${KEY_NAME})")
-
-# In case LastPass exitted non-zero we have no password
-if ! [ $? -eq 0 ]; then
-  echo "Unable to get password. Not trying to unlock."
-  exit 1
+lpass status > /dev/null
+LPASS_LOGIN_STATUS=$?
+if ! [ ${LPASS_LOGIN_STATUS} -eq 0 ]; then
+  if ! ( lpass login phil.goodwin@gmail.com ); then
+    echo "login failed"
+    exit 1    
+  fi
 fi
 
-# Fill password to ssh-add utility
-expect <<EOF >/dev/null
-spawn ssh-add ${KEY_NAME}
-expect "Enter passphrase"
-send "$PWD\n"
-expect eof
-EOF
+trap 'rm -f "${TMPFILE}"; echo "deleted temp file"' EXIT
+TMPFILE=$(mktemp -t DOWNLOADED_KEY_FILE)
+lpass show --notes github_key >> ${TMPFILE}
+
+if ! [ ${LPASS_LOGIN_STATUS} -eq 0 ]; then
+  lpass logout -f
+fi
+
+if [ ${SSH_HOURS} -eq -1 ]; then
+  ssh-add -q ${TMPFILE} || exit 1
+  echo "Key added -- will not expire"
+else
+  ssh-add -q -t ${SSH_HOURS}H ${TMPFILE} || exit 1
+  echo "Key added -- expires in ${SSH_HOURS} hours"
+fi
 
 # Check whether the key was added to the agent
-if ( ssh-add -l | grep -q "${KEY_NAME}" ); then
+if ( ssh-add -l | grep -q "${TMPFILE}" ); then
   echo "Key successfully added."
   exit 0
 else
